/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShootsIndexRouteImport } from './routes/shoots/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryMediaIdRouteImport } from './routes/library/$mediaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShootsIndexRoute = ShootsIndexRouteImport.update({
  id: '/shoots/',
  path: '/shoots/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryMediaIdRoute = LibraryMediaIdRouteImport.update({
  id: '/library/$mediaId',
  path: '/library/$mediaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/library': typeof LibraryIndexRoute
  '/shoots': typeof ShootsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/library': typeof LibraryIndexRoute
  '/shoots': typeof ShootsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/library/$mediaId': typeof LibraryMediaIdRoute
  '/library/': typeof LibraryIndexRoute
  '/shoots/': typeof ShootsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/library/$mediaId' | '/library' | '/shoots'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/library/$mediaId' | '/library' | '/shoots'
  id: '__root__' | '/' | '/library/$mediaId' | '/library/' | '/shoots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LibraryMediaIdRoute: typeof LibraryMediaIdRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ShootsIndexRoute: typeof ShootsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoots/': {
      id: '/shoots/'
      path: '/shoots'
      fullPath: '/shoots'
      preLoaderRoute: typeof ShootsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$mediaId': {
      id: '/library/$mediaId'
      path: '/library/$mediaId'
      fullPath: '/library/$mediaId'
      preLoaderRoute: typeof LibraryMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LibraryMediaIdRoute: LibraryMediaIdRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ShootsIndexRoute: ShootsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
