export const VERIFICATION_STATUS = {
  UNKNOWN: "UNKNOWN",
  NOT_NEEDED: "NOT_NEEDED",
  NEEDED: "NEEDED",
  APPLIED: "APPLIED",
  REJECTED: "REJECTED",
  VERIFIED: "VERIFIED",
} as const;

export type VerificationStatus =
  (typeof VERIFICATION_STATUS)[keyof typeof VERIFICATION_STATUS];
